spring:
  application:
    name: BabyDiary
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: evet
    password: LD3dC1kpv36K
    url: jdbc:mysql://localhost:3306/babydiary?userSSL=false
    platform: mysql
    initialization-mode: always